### ISSUE TITLE
Hjälp med att lägga "username" i frament_answers.xml

### ISSUE THREAD

**Issue by dhamark** [axelbirgersson/Pfi3_2015_Klara_S#2]
Jag behöver hjälp med att lägga användarnamnet man väljer på LogInFragment.java på TextViewen i fragment_answers.xml. Koden är kommenterad på raderna 37-39 och 50-55 i Answers.java. 

https://github.com/axelbirgersson/Pfi3_2015_Klara_S/blob/master/ScreenAndroid/src/main/java/se/mah/k3/klarappo/Answers.java

Tack på förhand!

**Comment by dhamark** [comment]
@antonnyman @isaklilja @k3larra

**Comment by axelbirgersson** [comment]
Detta problemet är nu löst!
